name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-gems
        restore-keys: |
          ${{ runner.os }}-gems
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies and run rubocop
      env:
        # Neccessary for jruby test coverage
        JRUBY_OPTS: "--debug"
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
        key: ${{ runner.os }}-gems
        restore-keys: |
          ${{ runner.os }}-gems
    - uses: ruby/setup-ruby@v1
    - name: Install dependencies and run RSpec
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        bundle exec rspec

    - uses: actions/upload-artifact@v2
      with:
        name: "Test Coverage"
        path: coverage/
